apiVersion: v1
kind: Service
metadata:
  name: kelascendikia-service
  namespace: kelascendikia
spec:
  type: LoadBalancer
  selector:
    app: kelascendikia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32100