apiVersion: v1
kind: Service
metadata:
  name: kelascendikia-service
  namespace: kelascendikia
spec:
  type: LoadBalancer
  externalIPs:
  - 103.175.220.186
  selector:
    app: kelascendikia
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 443
    - name: https
      protocol: TCP
      port: 443 #Port diakses dari ingress
      targetPort: 443 #Port yang dijalankan di aplikasi