apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kelascendikia-ingress
  namespace: kelascendikia
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kelascendikia.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kelascendikia-service
            port:
              number: 80
  - host: kelascendikia.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kelascendikia-service
            port:
              number: 80
